version: 2

jobs:
  build:
    working_directory: /go/src/github.com/figment-networks/near-indexer

    docker:
      - image: circleci/golang:1.14

    steps:
      - checkout
      - run: make build
      - run: make test